---
title: "Econometric Approach"
format: html
editor: visual
author: "Lennart Joop and Julia Daetz"
bibliography: references.bib
echo: false
warning: false
---

This document presents the econometric approach we used in our research project, as described in Milestone 3.

## Economic Model

```{mermaid}
%%|fig-cap: Flow Chart Empirical Strategy
%%{init: {"theme":"base", "themeVariables": {"background": "white"}}}%%
graph TD
    A[Research Question: How does the AfD vote share affect the migration decisions of EU foreigners in Germany?] --> B[Collect migration data]
    A --> C[Collect election data]
    B --> D[Address boundary mismatches between county districts and electoral districts using R]
    C --> D
    D --> E[Choose empirical strategy: Linear Regression]
    E --> F[Control for potential confounders, e.g. purchasing power, unemployment rate etc.]
    F --> G[Analyse AfD vote share's impact on migration decisions]
    G --> H[Address biases and limitations]

```

## Setting

**Endogenous Variable:** Xenophobia which we proxy by using AfD election results

**Main Outcome Variable:** The percentage change of the number of EU migrants

Our observation units are 299 German voting districts. We run four different regressions in four years. We want to find the impact of AfD vote share in the elections 2017 and 2021 on the change of EU migrants 3 months and 15 months after the election.

Because AfD vote shares are non-binary, we observe a treatment intensity instead of a treatment effect. Each unit of observation has a different treatment intensity which is based on the AfD vote shares.

## Mechanism

Due to our analysis being a simple regression, it is possible to test direct relationships between endogenous and main outcome variable. We plan on running simple regressions that just show the relation between our two main variables, reverse regressions to test for reverse causalities and simple regressions between our control variables and the main outcome variable.

## Sources of Bias and Identification

The connection we are trying to evaluate is hard to isolate cleanly. There are many factors that influence migration decisions in Europe:

-   economic opportunities such as potential incomes
-   access to healthcare
-   access to good education for the children
-   social factors such as child support, the access to other family members or a social group of people of similar culture
-   political climate in home and destination country

ACHTUNG @LENNART,das können wir so nicht schreiben. Das ist zwar plausibel, aber es steht so nicht in unserer Literatur und wir geben dafür auch keine Quellen an. Wir nehmen an, dass solche Überlegungen naheliegend sind, da wir Quellen haben, die solche Faktoren im HEIMATland untersuchen. (Bildungsstand, Kinder, Soziales Netz, Income etc.).

To isolate the effect of AfD vote shares we introduce control variables that should capture the influence of the other factors.

The control variable "Big Cities" is supposed to capture the impact of greater attractiveness of large cities due to better economic opportunities, better access to healthcare and other social factors.

The control variable "East Germany" is supposed to capture the impact of the differences between East and West Germany such as political climate, mentality and economic opportunities.

The control variable "Total amount of migrants" is supposed to capture the impact of the attractiveness of a region due to an already existing population of migrants which helps with integration and the access to a social group of people of similar culture.

The control variable "Unemployment" and "Purchase Power" are supposed to capture the impact of economic influences on migration decisions.

The control variable "Healthcare" is supposed to capture impact of access to healthcare on migration decisions.

We assume the overall direction of this bias is positive. Despite including several factors that could influence migration decisions there are still many factors that still could influence such a complex choice. We have an omitted variable bias. We are not able to include all of them in our model. This leads to an overestimation of the effect of AfD voting results on the change of EU migrants.

Another source of potential bias is the creation of our data set. We assign our federal district data to the voting districts by weighting the data via the share of area of the federal district that is in the voting district. This is just an approximation and differs from the real distribution of the population and migrants. Unfortunately, we have no way of removing or isolating this bias.We also don't know the direction of this bias. It could be positive if the data shows that voting districts with the highest AfD voting results occupy a larger share of the federal district area while actually having a smaller population. However, the reverse could also be true.

**Formulas**

[baseline OLS formulas:]{.underline}

*`main outcome variable <- endogenous variable`*

[with the following pairings:]{.underline}

**1)**\
MOV: Percentage change of EU migrants 31.12.2017 compared to 31.12.2016

EV: Vote results of the AFD on 24.09.2017

**2)**\
MOV: Percentage change of EU migrants 31.12.2018 compared to 31.12.2016

EV: Vote results of the AFD on 24.09.2017

**3)**\
MOV: Percentage change of EU migrants 31.12.2021 compared to 31.12.2020

EV: Vote results of the AFD on 26.09.2021

**4)**\
MOV: Percentage change of EU migrants 31.12.2022 compared to 31.12.2020

EV: Vote results of the AFD on 26.09.2021

[OLS formula with control variables:]{.underline}

`main outcome variable <- endogenous variable + control variables`

[with the following pairings:]{.underline}

**1)**\
MOV: Percentage change of EU migrants 31.12.2017 compared to 31.12.2016

EV: Vote results of the AFD on 24.09.2017

CV:

-   Dummy variable Big Cities (time indifferent)

-   Dummy variable East Germany (time indifferent)

-   Total amount of migrants on 31.12.2016

-   Unemployment rate on 31.12.2017

-   Average purchasing power on 31.12.2017

-   Access to hospital beds per 1000 inhabitants on 31.12.2017

**2)**\
MOV: Percentage change of EU migrants 31.12.2018 compared to 31.12.2016

EV: Vote results of the AFD on 24.09.2017

CV:

-   Dummy variable Big Cities (time indifferent)

-   Dummy variable East Germany (time indifferent)

-   Total amount of migrants on 31.12.2017

-   Unemployment rate on 31.12.2018

-   Average purchasing power on 31.12.2018

-   Access to hospital beds per 1000 inhabitants on 31.12.2018

**3)**\
MOV: Percentage change of EU migrants 31.12.2021 compared to 31.12.2020

EV: Vote results of the AFD on 26.09.2021

CV:

-   Dummy variable Big Cities (time indifferent)

-   Dummy variable East Germany (time indifferent)

-   Total amount of migrants on 31.12.2020

-   Unemployment rate on 31.12.2021

-   Average purchasing power on 31.12.2021

-   Access to hospital beds per 1000 inhabitants on 31.12.2021

**4)**\
MOV: Percentage change of EU migrants 31.12.2022 compared to 31.12.2020

EV: Vote results of the AFD on 26.09.2021

CV:

-   Dummy variable Big Cities (time indifferent)

-   Dummy variable East Germany (time indifferent)

-   Total amount of migrants on 31.12.2020

-   Unemployment rate on 31.12.2021

-   Average purchasing power on 31.12.2021

-   Access to hospital beds per 1000 inhabitants on 31.12.2021

## Treatment

We want to identify an effect of vote shares of the AfD on the migration decisions of EU foreigners in Germany. We assume that voting districts, which have a higher share of AfD voters, are more xenophobic. This xenophobia could lead to a decrease in the number of EU migrants in the following years. This decrease could either be motivated passively: higher AfD vote shares indicates higher xenophobia which decreases the live quality of EU foreigners, or actively: EU migrants inform themselves about the elections and choose not to live in regions with high shares of AfD voters.
